### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by KubikArmin** [Dansoftowner/14AB-A-Others#5]
Kell egy link a 14AB-A-plander docs repora
"A dokumentáció itt található:"
LINK LEGYEN A SZÖVEG

Cím: Valami menő cím, plander legyen benne
Névsor --> Csapattagok

**Comment by Dansoftowner** [comment]
A commit message a ":memo:" (így írd: `:memo:`) gitmoji-val kezdődjön
